"""fix recipe model

Revision ID: 175155e84791
Revises: 56f2323ef1e8
Create Date: 2025-12-12 08:47:44.300517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175155e84791'
down_revision = '56f2323ef1e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
